[run]
init_cmds = [
	["go", "test",  "-coverprofile", "cover.out", "--cover", "-v"],
	["go", "tool",  "cover", "-html=cover.out", "-o", "./cover.html"],
	["open", "./cover.html"],
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = []						# Directories to watch
watch_exts = [".go"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 1				# Time to wait until force kill
graceful_kill = true				# Wait for exit and before directly kill
cmds = [
	["go", "test",  "-coverprofile", "cover.out", "--cover", "-v"],
    ["go", "tool",  "cover", "-html=cover.out", "-o", "./cover.html"],
]									# Commands to run

[sync]
listen_addr = ":5050"
remote_addr = ":5050"